name: Create Version Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: butlerlogic/action-autotag@88cc59cb86a2de60e2b8494277d36e278b553f80
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        strategy: regex
        root: "ChangeLog.md"
        tag_prefix: "v"
