{
  "name": "CI",
  "on": {
    "push": [
      "master"
    ],
    "pull_request": null,
    "schedule": [
      {
        "cron": "0 10 * * 1"
      }
    ]
  },
  "jobs": [
    {
      "linter": {
        "env": {
          "OS": "ubuntu-latest",
          "QUICKLISP_DIST": "quicklisp",
          "LISP": "sbcl-bin"
        },
        "steps": [
          {
            "uses": "actions/checkout@v1"
          },
          {
            "uses": "40ants/setup-lisp@v1",
            "with": {
              "asdf-system": "40ants-ci"
            }
          },
          {
            "run": "qlot exec sblint *.asd",
            "shell": "bash"
          }
        ]
      }
    },
    {
      "run-tests": {
        "strategy": {
          "fail-fast": false,
          "matrix": {
            "os": [
              "ubuntu-latest",
              "macos-latest"
            ],
            "quicklisp-dist": [
              "quicklisp",
              "ultralisp"
            ],
            "lisp": [
              "sbcl-bin",
              "ccl-bin",
              "allegro"
            ]
          }
        },
        "env": {
          "OS": "${{ matrix.os }}",
          "QUICKLISP_DIST": "${{ matrix.quicklisp-dist}}",
          "LISP": "${{ matrix.lisp }}}"
        },
        "steps": []
      }
    }
  ]
}
