{
  "name": "CI",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    },
    "pull_request": null,
    "schedule": [
      {
        "cron": "0 10 * * 1"
      }
    ]
  },
  "jobs": {
    "linter": {
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin"
      },
      "steps": [
        {
          "uses": "actions/checkout@v1"
        },
        {
          "uses": "40ants/setup-lisp@v1",
          "with": {
            "asdf-system": "40ants-ci"
          }
        },
        {
          "run": "qlot exec sblint *.asd",
          "shell": "bash"
        }
      ]
    },
    "run-tests": {
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "os": [
            "ubuntu-latest",
            "macos-latest"
          ],
          "quicklisp-dist": [
            "quicklisp",
            "ultralisp"
          ],
          "lisp": [
            "sbcl-bin",
            "ccl-bin",
            "allegro"
          ]
        }
      },
      "env": {
        "OS": "${{ matrix.os }}",
        "QUICKLISP_DIST": "${{ matrix.quicklisp-dist}}",
        "LISP": "${{ matrix.lisp }}}"
      },
      "steps": [
        {
          "uses": "actions/checkout@v1"
        },
        {
          "uses": "40ants/setup-lisp@v1",
          "with": {
            "asdf-system": "40ants-ci",
            "qlfile-template": "{% ifequal quicklisp_dist \"ultralisp\" %}\ndist ultralisp http://dist.ultralisp.org\n{% endifequal %}\n\ngithub mgl-pax svetlyak40wt/mgl-pax :branch mgl-pax-minimal"
          }
        },
        {
          "uses": "40ants/run-tests@v2",
          "with": {
            "asdf-system": "40ants-ci",
            "coveralls-token": "\n${{ matrix.lisp == 'sbcl-bin' &&\n    matrix.os == 'ubuntu-latest' &&\n    matrix.quicklisp-dist == 'ultralisp' &&\n    secrets.github_token }}"
          }
        }
      ]
    }
  }
}
